services:
  postgres:
    platform: linux/amd64
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=dog_walker_user
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
