default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: dog_walker_user
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  database: dog_walker_dev

test:
  <<: *default
  database: dog_walker_test

production:
  <<: *default
  database: dog_walker_prod
